typography_spectrum: 0.7634787468705326
color:
  brandStrength: 0.6563615882769227
  lightness: 0.3233537864871323
  saturation: 0.16302864789031446
  rhythmicContrast: 0.4279615576379001
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
layout_spectrum: 0.8322660634294152
author:
  name: Jason
  email: jasonhendry@gmail.com
  url: jasonhendry.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0173a46c-4fb2-4f39-a0e3-3ddff302515e.svg
name: Beats & Bytes
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7f48b86b-49eb-44a2-b42e-116c611c9790.svg
title: What happens when I press this button...?
description: Did I do that?
